enabled_recipes:
  - rspec
  - mocha
  - factory_girl
  - infinity_test
  - cucumber
  - haml
  - jquery
  - simple_form
  # - nifty_layout
  - web_app_theme
  - simple_navigation
  - kaminari
  - static
  - has_scope
  - simple_enum
  - andand
  - auto_protect_model_attributes
  # - cream
  - annotate_models
  # - cappuccino
  # - adhearsion
  # - heroku
  # - github

rspec:
  mocha: true

cucumber:
  backend: capybara

web_app_theme:
  theme: default

cappuccino:
  cib_app: true

cream:
  strategy: admin_flag
  roles:
    - 'guest'
    - 'admin'

github:
  username: your_username
  repo_name: your_repo_name
