enabled_recipes:
  - rspec
  - mocha
  - factory_girl
  - infinity_test
  - cucumber
  - haml
  - jquery
  - simple_form
  # - nifty_layout
  - web_app_theme
  - simple_navigation
  - kaminari
  - static
  - has_scope
  - inherited_resources
  - simple_enum
  - meta_search_where # meta_search and meta_where
  - andand
  - auto_protect_model_attributes
  # - cream
  - annotate_models
  # - cappuccino
  # - adhearsion
  # - heroku
  # - github
  # - capistrano
  # - newrelic_rpm

cucumber:
  backend: capybara

web_app_theme:
  theme: default

cappuccino:
  cib_app: true

cream:
  strategy: admin_flag
  roles:
    - 'guest'
    - 'admin'

capistrano:
  app_name: someapp
  server: alpha.someapp.com
  git_repo: git@github.com:aentos/app.git

github:
  username: your_username
  repo_name: your_repo_name

newrelic_rpm:
  account_id: 12345
